// <auto-generated />
using System;
using System.Collections.Generic;
using MeroSwasthya.Modules.Maternal.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeroSwasthya.Modules.Maternal.Infrastructure.Migrations
{
    [DbContext(typeof(MaternalDbContext))]
    [Migration("20260929151603_AddDeliveries")]
    partial class AddDeliveries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("maternal")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeroSwasthya.Modules.Maternal.Domain.AncContact", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<int>("ContactNo")
                        .HasColumnType("integer")
                        .HasColumnName("contact_no");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<List<string>>("DangerSigns")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("danger_signs");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("DoneAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("done_at");

                    b.Property<DateOnly>("DueAt")
                        .HasColumnType("date")
                        .HasColumnName("due_at");

                    b.Property<string>("Findings")
                        .HasColumnType("jsonb")
                        .HasColumnName("findings");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("patient_id");

                    b.Property<string>("PregnancyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pregnancy_id");

                    b.Property<string>("ProviderUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_user_id");

                    b.Property<string>("Referral")
                        .HasColumnType("jsonb")
                        .HasColumnName("referral");

                    b.Property<string>("TriageLevel")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("triage_level");

                    b.Property<List<string>>("TriageReasons")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("triage_reasons");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<int>("WeekTarget")
                        .HasColumnType("integer")
                        .HasColumnName("week_target");

                    b.HasKey("Id")
                        .HasName("pk_anc_contacts");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_anc_contacts_updated_at");

                    b.HasIndex("PatientId", "DoneAt")
                        .HasDatabaseName("ix_anc_contacts_patient_id_done_at");

                    b.HasIndex("PregnancyId", "ContactNo")
                        .IsUnique()
                        .HasDatabaseName("ix_anc_contacts_pregnancy_id_contact_no");

                    b.ToTable("anc_contacts", "maternal");
                });

            modelBuilder.Entity("MeroSwasthya.Modules.Maternal.Domain.Delivery", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("BabySex")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("baby_sex");

                    b.Property<double?>("BabyWeightKg")
                        .HasColumnType("double precision")
                        .HasColumnName("baby_weight_kg");

                    b.Property<List<string>>("Complications")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("complications");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("mode");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("outcome");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("patient_id");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("place");

                    b.Property<string>("PregnancyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pregnancy_id");

                    b.Property<string>("RecordedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_deliveries");

                    b.HasIndex("PregnancyId")
                        .HasDatabaseName("ix_deliveries_pregnancy_id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_deliveries_updated_at");

                    b.HasIndex("PatientId", "DeliveredAt")
                        .HasDatabaseName("ix_deliveries_patient_id_delivered_at");

                    b.ToTable("deliveries", "maternal");
                });

            modelBuilder.Entity("MeroSwasthya.Modules.Maternal.Domain.Pregnancy", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("BirthPlan")
                        .HasColumnType("jsonb")
                        .HasColumnName("birth_plan");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateOnly>("Edd")
                        .HasColumnType("date")
                        .HasColumnName("edd");

                    b.Property<int>("Gravida")
                        .HasColumnType("integer")
                        .HasColumnName("gravida");

                    b.Property<DateOnly?>("Lmp")
                        .HasColumnType("date")
                        .HasColumnName("lmp");

                    b.Property<int>("Para")
                        .HasColumnType("integer")
                        .HasColumnName("para");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("patient_id");

                    b.Property<string>("RegisteredByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("registered_by_user_id");

                    b.Property<List<string>>("RiskFactors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("risk_factors");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("risk_level");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_pregnancies");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_pregnancies_updated_at");

                    b.HasIndex("PatientId", "Status")
                        .HasDatabaseName("ix_pregnancies_patient_id_status");

                    b.ToTable("pregnancies", "maternal");
                });
#pragma warning restore 612, 618
        }
    }
}
