<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\MeroSwasthya.Shared\MeroSwasthya.Shared.csproj" />
    <ProjectReference Include="..\..\Patients\MeroSwasthya.Modules.Patients\MeroSwasthya.Modules.Patients.csproj" />
    <ProjectReference Include="..\..\Maternal\MeroSwasthya.Modules.Maternal\MeroSwasthya.Modules.Maternal.csproj" />
    <ProjectReference Include="..\..\Clinical\MeroSwasthya.Modules.Clinical\MeroSwasthya.Modules.Clinical.csproj" />
    <ProjectReference Include="..\..\Auth\MeroSwasthya.Modules.Auth\MeroSwasthya.Modules.Auth.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="MeroSwasthya.UnitTests" />
    <InternalsVisibleTo Include="MeroSwasthya.ContractTests" />
    <InternalsVisibleTo Include="MeroSwasthya.Api" />
  </ItemGroup>
</Project>
