<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\MeroSwasthya.Shared\MeroSwasthya.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="MeroSwasthya.UnitTests" />
    <InternalsVisibleTo Include="MeroSwasthya.ContractTests" />
    <InternalsVisibleTo Include="MeroSwasthya.Api" />
  </ItemGroup>
</Project>
