// <auto-generated />
using System;
using System.Collections.Generic;
using MeroSwasthya.Modules.Patients.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeroSwasthya.Modules.Patients.Infrastructure.Migrations
{
    [DbContext(typeof(PatientsDbContext))]
    [Migration("20260928063102_InitialPatients")]
    partial class InitialPatients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("patients")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeroSwasthya.Modules.Patients.Domain.Patient", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<List<string>>("Allergies")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("allergies");

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("blood_group");

                    b.Property<List<string>>("ChronicConditions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("chronic_conditions");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("emergency_contact_phone");

                    b.Property<string>("Municipality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("municipality");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("sex");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<int?>("Ward")
                        .HasColumnType("integer")
                        .HasColumnName("ward");

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_patients_owner_user_id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_patients_updated_at");

                    b.ToTable("patients", "patients");
                });
#pragma warning restore 612, 618
        }
    }
}
