<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\MeroSwasthya.Shared\MeroSwasthya.Shared.csproj" />
    <ProjectReference Include="..\..\Patients\MeroSwasthya.Modules.Patients\MeroSwasthya.Modules.Patients.csproj" />
    <ProjectReference Include="..\..\Catalog\MeroSwasthya.Modules.Catalog\MeroSwasthya.Modules.Catalog.csproj" />
    <ProjectReference Include="..\..\Audit\MeroSwasthya.Modules.Audit\MeroSwasthya.Modules.Audit.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="MeroSwasthya.UnitTests" />
    <InternalsVisibleTo Include="MeroSwasthya.ContractTests" />
    <InternalsVisibleTo Include="MeroSwasthya.Api" />
  </ItemGroup>
</Project>
