// <auto-generated />
using System;
using System.Collections.Generic;
using MeroSwasthya.Modules.Grants.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeroSwasthya.Modules.Grants.Infrastructure.Migrations
{
    [DbContext(typeof(GrantsDbContext))]
    partial class GrantsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("grants")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeroSwasthya.Modules.Grants.Domain.AccessGrant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AccessUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_until");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("jti");

                    b.Property<bool>("LongLived")
                        .HasColumnType("boolean")
                        .HasColumnName("long_lived");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("patient_id");

                    b.Property<DateTime?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<string>("RedeemedByUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("redeemed_by_user_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("scope");

                    b.Property<List<string>>("Sections")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("sections");

                    b.HasKey("Id")
                        .HasName("pk_access_grants");

                    b.HasIndex("Jti")
                        .IsUnique()
                        .HasDatabaseName("ix_access_grants_jti");

                    b.HasIndex("PatientId", "CreatedAt")
                        .HasDatabaseName("ix_access_grants_patient_id_created_at");

                    b.HasIndex("RedeemedByUserId", "PatientId")
                        .HasDatabaseName("ix_access_grants_redeemed_by_user_id_patient_id");

                    b.ToTable("access_grants", "grants");
                });
#pragma warning restore 612, 618
        }
    }
}
